apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: hikaricp
  name: hikaricp
  namespace: hikaricp
spec:
  replicas: 1
  selector:
    matchLabels:
      app: hikaricp
  strategy: {}
  template:
    metadata:
      labels:
        app: hikaricp
    spec:
      containers:
      - image: ghcr.io/levi106/hikaricp-sample-web:main-ms
        name: hikaricp
        env:
          - name: SPRING_DATASOURCE_URL
            valueFrom:
              secretKeyRef:
                name: db
                key: connectionstring
          - name: APPLICATIONINSIGHTS_CONNECTION_STRING
            valueFrom:
              secretKeyRef:
                name: ai
                key: connectionstring
        resources:
          requests:
            memory: "32Mi"
            cpu: "100m"
          limits:
            memory: "512Mi"
            cpu: "500m"
---
apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    app: hikaricp
  name: hikaricp
  namespace: hikaricp
spec:
  ports:
  - port: 8080
    protocol: TCP
    targetPort: 8080
  selector:
    app: hikaricp
  type: LoadBalancer
status:
  loadBalancer: {}
